### ISSUE TITLE
Namespace Design Tokens

### ISSUE THREAD

**Issue by 4aficiona2** [lyne-design-system/lyne-design-tokens#284]
Lyne Design Tokens should be namespaced to avoid name clashes with other custom properties.

Proposal: Either use `l-PROPERTYNAME` which might still lead to a name clash since it is not very specific or use `lyne-PROPERTYNAME` which is much more specific but a bit longer.

My suggestion is to use `lyne-PROPERTYNAME`

**Comment by jeripeierSBB** [comment]
Is tracked by new issue (resp. card at the moment).
